#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Aug 13 09:32:33 2020

@author: eason
"""
from mcpi.minecraft import Minecraft
mc = Minecraft.create()
x,y,z = mc.player.getPos()

import random
for i in range(20):
    r = random.randrange(1,5)
    if r== 1:
        mc.setBlocks(x,y,z,x+4,y,z,1)
        x = x+4
    elif r== 2:
        mc.setBlocks(x,y,z,x-4,y,z,1)
        x = x-4
        y=y-4
    elif r== 3:
        mc.setBlocks(x,y,z,x,y,z+4,1)
        z = z+4
    elif r== 4:
        mc.setBlocks(x,y,z,x,y,z-4,1)
        z = z-4
        y=y+4
        
        