#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Aug 11 16:16:40 2020

@author: eason
"""


from mcpi.minecraft import Minecraft
mc = Minecraft.create()
while True:
    hits = mc.events.pollBlockHits()
    if len(hits)>0:
        hit = hits[0]
        x,y,z = hit.pos.x, hit.pos.y, hit.pos.z
        block = mc.createExplosion(x,y,z) 