#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Aug 12 12:19:20 2020

@author: eason
"""

from mcpi.minecraft import Min
x,y,z = mc.player.getecraft
mc = Minecraft.create()Pos()

def plantTree(x,y,z):
    mc.setBlocks(x+1,y+5,z+1,x-1,y+3,z-1,18)
    mc.setBlocks(x,y,z,x,y+4,z,17)
for h in range(0,50,3):
    for i in range(0,50,3):
        plantＴree(x+i,y,z+h)