#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Aug 11 15:13:16 2020

@author: eason
"""

from mcpi.minecraft import Minecraft 
mc = Minecraft.create()


x,y,z = mc.player.getPos()
mc.setSign(x,y,z,63,0,"123123456")